### ISSUE TITLE
Капча

### ISSUE THREAD

**Issue by daniilak** [loadlost/RR-Parser#1]
Предлагаю взять код решалки капчи отсюда
https://huggingface.co/spaces/docparser/Text_Captcha_breaker

**Comment by loadlost** [comment]
спасибо за наводку, интересная мысль. по результатам беглого теста, работает даже быстрее и точнее, чем антикапча, и это на моём унылом железе. буду внедрять. осталось придумать, что делать с 3 миллиардами предоплаченных капч.

единственное, что заметил, модель явно путается, если в капче есть одновременно w и m. это не большая проблема, просто любопытный момент.

**Comment by daniilak** [comment]
Подобных моделей достаточно много на hf/kaggle, советую посмотреть и использовать. В рабочих моментах отлично используется

**Comment by loadlost** [comment]
добавил модель и часть кода из [Text_Captcha_breaker](https://huggingface.co/spaces/docparser/Text_Captcha_breaker), работает, как часы. ещё раз, спасибо за идею.
